### ISSUE TITLE
Change webjob to use a blob trigger instead of a queue message for image resize

### ISSUE THREAD

**Issue by SyntaxC4** [azure-appservice-samples/ContosoMoments#33]
Currently there is a need to call ResizeQueue from the client side. This is a function which is required to be called which means it should be triggered as part of the insert function for the database to ensure that the image is resized by the WebJob.

The delete function should stay as a queue trigger.

**Comment by yochay** [comment]
Furthermore, if we are looking to make this change in the API backend, we should consider issue [#34](https://github.com/azure-appservice-samples/ContosoMoments/issues/34)

**Comment by lindydonna** [comment]
The problem is that the mobile client needs there to be a record when it does its file upload. It could potentially do the file upload first, but then we're still putting logic in the client. 

A better solution is to just use blob triggers to do the image resize. I tried this with the latest webjobs SDK, but I still saw 10 minute latency before the blob was actually picked up. I need to investigate this further. 

The other problem is that the code changes the content type of the source image during the resize, since the mobile client does not set it. This causes another blob trigger to fire, since it changes the underlying blob.

In theory, we could just remove this content type logic, since on the web, the source image is always shown in the context of an HTML page and doesn't need its own content type. The resized images do need it, but their content type is set during the resize operation.

**Comment by lindydonna** [comment]
We'll fix this by using an Azure Function with a blob trigger instead.
